export const GET_LIST_CROSSWORDS = 'GET_LIST_CROSSWORDS';
export const GET_LIST_CROSSWORDS_FULFILLED = 'GET_LIST_CROSSWORDS_FULFILLED';
export const GET_LIST_CROSSWORDS_REJECTED = 'GET_LIST_CROSSWORDS_REJECTED';

export const GET_BOARD = 'GET_BOARD';

export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_FULFILLED = 'GET_PROFILE_FULFILLED';
export const GET_PROFILE_REJECTED = 'GET_PROFILE_REJECTED';

export const LOGIN_FULFILLED = 'LOGIN_FULFILLED';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_REJECTED = 'LOGIN_REJECTED';
export const LOGIN = 'LOGIN';
export const REGISTER = 'REGISTER';
